In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import pandas as pd

In [2]:
df=pd.read_csv("insurance_data.csv")
df

age  bought_insurance
0    22                 0
1    25                 0
2    47                 1
3    52                 0
4    46                 1
5    56                 1
6    55                 0
7    60                 1
8    62                 1
9    61                 1
10   18                 0
11   28                 0
12   27                 0
13   29                 0
14   49                 1
15   55                 1
16   25                 1
17   58                 1
18   19                 0
19   18                 0
20   21                 0
21   26                 0
22   40                 1
23   45                 1
24   50                 1
25   54                 1
26   23                 0

In [3]:
X=df[['age']]
y=df['bought_insurance']

In [4]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [5]:
X_train

age
14   49
23   45
4    46
13   29
15   55
10   18
8    62
3    52
12   27
20   21
6    55
17   58
11   28
24   50
26   23
16   25
21   26
22   40
25   54
18   19
5    56

In [6]:
X_test

age
2    47
9    61
19   18
0    22
7    60
1    25

In [7]:
y_train

14    1
23    1
4     1
13    0
15    1
10    0
8     1
3     0
12    0
20    0
6     0
17    1
11    0
24    1
26    0
16    1
21    0
22    1
25    1
18    0
5     1
Name: bought_insurance, dtype: int64

In [8]:
y_test

2     1
9     1
19    0
0     0
7     1
1     0
Name: bought_insurance, dtype: int64

In [9]:
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [10]:
model.predict(X_test)

array([1, 1, 0, 0, 1, 0])

In [11]:
model.score(X_test,y_test)

1.0

In [15]:
model.predict([[10]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [16]:
model.predict_proba(X_test)

array([[0.28044974, 0.71955026],
       [0.07116367, 0.92883633],
       [0.9188929 , 0.0811071 ],
       [0.87681647, 0.12318353],
       [0.07923724, 0.92076276],
       [0.83397151, 0.16602849]])