In [2]:
import numpy as np

Valid Sudoku

In [29]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [30]:
print(np.sum(s,axis=1))
print(np.sum(s,axis=0))

[45 45 45 45 45 45 45 45 45]
[45 45 45 45 45 45 45 45 45]


In [56]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [32]:
#Get the shape of the matrix.
print(data.shape)

(5, 3)


In [34]:
#Find the average age of students.
print(np.mean(data[:,0]))

18.4


In [36]:
#Extract Math marks of all students.
print(data[:,1])

[85 92 76 65 90]


In [37]:
#Find the highest Science mark.

In [38]:
print(np.max(data[:,2]))

95


In [39]:
#Get details of the student who scored more than 90 in Math.
print(data[data[:,1]>90])

[[19 92 88]]


In [40]:
#Increase Math marks of all students by 5.

In [44]:
data[:,1]+=5
data
#Increase Math marks of all students by 5.

array([[ 18,  95,  78],
       [ 19, 102,  88],
       [ 17,  86,  95],
       [ 18,  75,  70],
       [ 20, 100,  85]])

In [45]:
#Find how many students are younger than 19.

In [46]:
print(data[data[:,0]>19])

[[ 20 100  85]]


In [47]:
#Calculate the average marks in each subject (column-wise mean).
print(np.mean(data[:,1],axis=0))

91.6


In [48]:
print(np.mean(data[:,2],axis=0))

83.2


In [52]:
#Get data of students who scored at least 80 in both subjects.
print(data[(data[:,2]>=80) & (data[:,1]>=80)])

[[ 19 102  88]
 [ 17  86  95]
 [ 20 100  85]]


In [57]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])