In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,])
arr

array([1, 2, 3, 4])

In [5]:
#list
a=[1,2,3,4,'a']
a

[1, 2, 3, 4, 'a']

In [6]:
np.array(a)

array(['1', '2', '3', '4', 'a'], dtype='<U21')

In [7]:
#for array all the list elements are changed to string as numpy arrays only allows homogenous elements

In [8]:
l=[[1,2,3],[4,5,6],[7,8,9]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation methods


In [9]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
#linear spacing between numbers
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [16]:
np.linspace(1,10,2)

array([ 1., 10.])

In [21]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [18]:
#linspace is generating the array based on start end and the number of elements and the number of elements will be having an equal spaces

Random generation functions

In [19]:
np.random.rand(5)

array([0.30173929, 0.15730899, 0.16907475, 0.07986179, 0.92849136])

In [23]:
#standardised values -3 to 3
np.random.randn(10)

array([ 2.58597828, -1.33429328, -0.56706688, -0.13884955,  0.15842288,
       -1.75828548, -0.00875773, -2.05727471, -1.6731632 , -1.30678744])

In [25]:
np.random.randint(10,20,5)

array([14, 14, 16, 14, 12])

Attributes


In [26]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr.shape

(3, 3)

In [28]:
arr.size

9

In [29]:
arr.dtype

dtype('int64')

Methods

In [30]:
arr.min()

np.int64(1)

In [31]:
arr.max()

np.int64(9)

In [32]:
arr.sum()

np.int64(45)

In [33]:
#column sum
np.sum(arr,axis=0)

array([12, 15, 18])

In [34]:
#row sum
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [35]:
arr.mean()

np.float64(5.0)

In [38]:
arr.std() #st.deviation

np.float64(2.581988897471611)

In [39]:
arr.argmax() #index of max element

np.int64(8)

In [40]:
arr.argmin() #index of min element

np.int64(0)

Reshaping

In [43]:
arr1=np.arange(1,31)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [44]:
arr1.reshape(6,5) #6rows and 5 cols

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [45]:
arr1.reshape(5,6) #5 rows and 6 cols

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])