In [2]:
import numpy as np

In [3]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [4]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [5]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1-a2

array([-5, -5, -5, -5, -5])

In [7]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1//a2

array([0, 0, 0, 0, 0])

In [9]:
a1+10

array([11, 12, 13, 14, 15])

In [10]:
arr=np.arange(1,26).reshape(5,5)
arr+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [11]:
#deep and shallow copy
original = np.array([1, 2, 3, 4])
shallow = original.view()
shallow[0] = 100
print(original)  # Output: [100   2   3   4]

[100   2   3   4]


In [12]:
original = np.array([1, 2, 3, 4])
deep = original.copy()
deep[0] = 100
print(deep)
print(original)  # Output: [1 2 3 4]

[100   2   3   4]
[1 2 3 4]


In [13]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[4,5,6],[9,10,12],[3,2,1]])
A@B #matrix multiplication

array([[ 31,  31,  33],
       [ 79,  82,  90],
       [127, 133, 147]])

In [14]:
np.dot(A,B) #dot product

array([[ 31,  31,  33],
       [ 79,  82,  90],
       [127, 133, 147]])

In [15]:
np.cross(A,B) #cross product

array([[ -3,   6,  -3],
       [  0,   6,  -5],
       [-10,  20, -10]])

In [16]:
np.transpose(A)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [17]:
np.invert(A)

array([[ -2,  -3,  -4],
       [ -5,  -6,  -7],
       [ -8,  -9, -10]])

In [18]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [21]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [22]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
c=np.arange(1,17).reshape(4,4)

In [27]:
#equal division splits
np.hsplit(c,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [28]:
np.vsplit(c,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]