In [46]:
import numpy as np

In [50]:
arr=np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
arr[3]

np.int64(13)

In [52]:
arr[1:6]

array([11, 12, 13, 14, 15])

In [53]:
arr[:6]

array([10, 11, 12, 13, 14, 15])

In [54]:
arr[1:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [55]:
arr[3:6:2]

array([13, 15])

In [56]:
arr[3:21:2]

array([13, 15, 17, 19])

In [57]:
arr[3::2]

array([13, 15, 17, 19])

matrix indexing

In [59]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [66]:
arr[0] #row only

array([1, 2, 3, 4, 5])

In [61]:
arr[0,0]

np.int64(1)

In [64]:
arr[5,4]

np.int64(30)

In [65]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [67]:
arr[:,0] #col only

array([ 1,  6, 11, 16, 21, 26])

boolean indexing

In [72]:
arr=np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [69]:
bool_index=arr%2==0
bool_index

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [70]:
arr=arr[bool_index]

In [71]:
arr


array([10, 12, 14, 16, 18])